# Generated by Django 4.2.21 on 2025-06-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='member',
            name='driver_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='headshot_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name_acronym',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
