# Generated by Django 4.2.21 on 2025-06-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_member_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='headshot_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
