# Generated by Django 4.2.21 on 2025-06-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_base_team_chassis_team_director_team_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='apisports_id',
            field=models.PositiveIntegerField(blank=True, help_text='APISports F1 API ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='apisports_id',
            field=models.PositiveIntegerField(blank=True, help_text='APISports F1 API ID', null=True, unique=True),
        ),
    ]
