# Generated by Django 4.2.21 on 2025-06-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_base_team_chassis_team_director_team_engine_and_more'),
        ('races', '0002_race_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='distance',
            field=models.PositiveIntegerField(blank=True, help_text='Distance in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='fastest_lap',
            field=models.PositiveIntegerField(blank=True, help_text='Fastest lap in seconds', null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='fastest_lap_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastest_lap_driver', to='teams.member'),
        ),
        migrations.AddField(
            model_name='race',
            name='laps',
            field=models.PositiveIntegerField(blank=True, help_text='Number of laps', null=True),
        ),
    ]
