# Generated by Django 4.2.21 on 2025-06-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_race_distance_race_fastest_lap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='race',
            name='fastest_lap',
        ),
        migrations.RemoveField(
            model_name='race',
            name='fastest_lap_driver',
        ),
        migrations.RemoveField(
            model_name='race',
            name='laps',
        ),
        migrations.AddField(
            model_name='position',
            name='grid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='laps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='pit_stop_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
