# Generated by Django 4.2.21 on 2025-06-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_remove_race_distance_remove_race_fastest_lap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='apisports_id',
            field=models.PositiveIntegerField(blank=True, help_text='APISports F1 API ID', null=True, unique=True),
        ),
    ]
