name: Django Tests

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: formulated_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      # Django settings
      DJANGO_SECRET_KEY: 'test-secret-key-for-ci'
      DEBUG: 'False'
      DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/formulated_test'
      ALLOWED_HOSTS: 'localhost,127.0.0.1'
      
      # CORS settings for tests
      CORS_ALLOW_ALL_ORIGINS: 'True'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt

    - name: Create logs directory
      run: |
        mkdir -p api/logs

    - name: Run Django migrations
      working-directory: ./api
      run: |
        python manage.py migrate

    - name: Run Django tests
      working-directory: ./api
      run: |
        python manage.py test --verbosity=2

    - name: Run Django tests with coverage (optional)
      working-directory: ./api
      run: |
        pip install coverage
        coverage run --source='.' manage.py test
        coverage report
        coverage xml
      continue-on-error: true

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./api/coverage.xml
        directory: ./api
        fail_ci_if_error: false
      continue-on-error: true 